# Generated by Django 5.0.6 on 2024-06-06 11:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo_delete_image_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='body',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
