# Generated by Django 5.0.6 on 2024-06-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_body_subtitle_body_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Contact_Background',
        ),
    ]
