# Generated by Django 5.0.6 on 2024-06-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
