# Generated by Django 5.0.6 on 2024-06-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_background_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='background',
            table='services_model',
        ),
    ]
