# Generated by Django 5.0.6 on 2024-06-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_background_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Background',
            new_name='Background_content',
        ),
        migrations.AlterModelTable(
            name='background_content',
            table=None,
        ),
    ]
