# Generated by Django 4.2.5 on 2024-06-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='whatshappening',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='whatshappening',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
