# Generated by Django 5.0.6 on 2024-06-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_service_subtitle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Service_content',
        ),
    ]
