# Generated by Django 5.0.6 on 2024-06-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Book_Appointment',
        ),
    ]
