# Generated by Django 5.0.6 on 2024-06-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_appointment_book_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_appointment',
            name='access_code',
        ),
        migrations.RemoveField(
            model_name='book_appointment',
            name='city_state_zipcode',
        ),
    ]
