# Generated by Django 4.2.5 on 2024-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='about/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='body',
            name='images',
        ),
    ]
