# Generated by Django 4.2.5 on 2024-06-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_images_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Body',
            new_name='Content',
        ),
    ]
