# Generated by Django 4.2.5 on 2024-06-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_body_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='Background',
        ),
    ]
