# Generated by Django 5.0.6 on 2024-06-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_header_background'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='background',
            table='about_model',
        ),
    ]
