# Generated by Django 5.0.6 on 2024-06-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_background_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='background',
            table=None,
        ),
    ]
